version: '3'
services:
  web:
    build: .
    command: sh -c "uvicorn main:app --reload --port=10001 --host=0.0.0.0"
    env_file:
      - .env
    ports:
      - 10001:10001
    volumes:
      - .:/app